redirectsOrigin = "config"
headers = []

[functions]

[functions."*"]

[[plugins]]
origin = "ui"
package = "@netlify/plugin-lighthouse"

[plugins.inputs]

[build]
publish = "/home/user/workspace/mobile/dist"
publishOrigin = "config"
commandOrigin = "config"
base = "/home/user/workspace/mobile"
command = "npx expo export --platform web"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]